FROM itsafeaturemythic/python38_payload:0.0.9

RUN pip uninstall -y mythic_payloadtype_container
RUN pip install --index-url https://test.pypi.org/simple/ mythic_payloadtype_container==0.0.93
#RUN pip install mythic_payloadtype_container==0.0.48